routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'sentinel:admin,vendedor'], function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    /**
    * Rutas de usuario
    */    
    Route::group(['middleware' => 'sentinel:admin'], function () {
        Route::resource('users', 'AuthController');
        Route::get('usersactivate/{id}/{estado}', 'AuthController@activate')->name('usersactivate');
        Route::any('userssearch', 'AuthController@search')->name('userssearch');
    });
    Route::any('users_update/{user}', 'AuthController@show')->name('users_update');
    /**
    * Actualizar los datos de usuario por el propio usuario(Nombre, Apellido y Correo)
    */  
    Route::put('usersupdate/{id}', 'AuthController@update_user')->name('usersupdate');

    Route::resource('clients', 'ClienteController');
    Route::any('clientssearch', 'ClienteController@search')->name('clientssearch');
    
});
/*
*Rutas Publicas
*/
Route::post('sendlogin', 'AuthController@login')->name('sendlogin');
Route::get('userslogout', 'AuthController@logout')->name('userslogout');
Route::get('/', function () {
    //Sentinel::registerAndActivate(['email'=>'car@admin.com','password'=>'1234']);
    return view('vendor.adminlte.login');
})->name("/");

resources/views/edit.blade.php
<div class="row">
    <div class="text-right">
        <a href="{{route('users.show',Sentinel::getUser())}}" class=" btn btn-info">Editar mi perfil</a>
    </div>
</div>
<hr>

resources/views/flash_message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
	{!! $message !!}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true"><i class="fa fa-times-circle text-white"></i></span>
	</button>
</div>
@endif
@if ($message = Session::get('error'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
	{!! $message !!}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true"><i class="fa fa-times-circle text-white"></i></span>
	</button>
</div>
@endif
@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-dismissible fade show" role="alert">
	{!! $message !!}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true"><i class="fa fa-times-circle text-white"></i></span>
	</button>
</div>
@endif
@if ($message = Session::get('info'))
<div class="alert alert-info alert-dismissible fade show" role="alert">
	{!! $message !!}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true"><i class="fa fa-times-circle text-white"></i></span>
	</button>
</div>
@endif