routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'sentinel:admin,vendedor'], function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    /**
    * Rutas de usuario
    */    
    Route::group(['middleware' => 'sentinel:admin'], function () {
        Route::resource('users', 'AuthController');
        Route::get('usersactivate/{id}/{estado}', 'AuthController@activate')->name('usersactivate');
        Route::any('userssearch', 'AuthController@search')->name('userssearch');
    });
    Route::any('users_update/{user}', 'AuthController@show')->name('users_update');
    /**
    * Actualizar los datos de usuario por el propio usuario(Nombre, Apellido y Correo)
    */  
    Route::put('usersupdate/{id}', 'AuthController@update_user')->name('usersupdate');

    Route::resource('clients', 'ClienteController');
    Route::any('clientssearch', 'ClienteController@search')->name('clientssearch');
    
});
/*
*Rutas Publicas
*/
Route::post('sendlogin', 'AuthController@login')->name('sendlogin');
Route::get('userslogout', 'AuthController@logout')->name('userslogout');
Route::get('/', function () {
    //Sentinel::registerAndActivate(['email'=>'car@admin.com','password'=>'1234']);
    return view('vendor.adminlte.login');
})->name("/");

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Sentinel;
use Validator;
use Session;
use Redirect;
use URL;
use Carbon\Carbon;
use DB;
#DB
use App\Client;

class ClienteController extends Controller
{
    private $rules = [
        'nombre'    => 'required|min:3',
        'documento' => 'required|min:3',
        'email'     => 'required|email'
    ];
    private $messages = [
        '*.required'  => 'Campo obligatorio.',
        '*.min'       => 'Este campo debe ser mayor de :min caracteres.',
        'email.email' => 'Ingrese email valido',        
    ];
    /**
    * Listar todos los clientes de la BD
    */
    public function index(){
        try{
            $clients=Client::paginate(10);
            $search='';
            return view('clientes.index',compact('clients','search'));
        }catch(\Exception $ex){
            Session::flash('error', 'Ha surgido un error');
            return Redirect::to(URL::previous());
        }
    }

    /**
    * Función para crear usuarios(Muestra la vista)
    */
    public function create(){
        try{
            return View("clientes.register");
        }catch(\Exception $ex){
            Session::flash('error', 'Ha surgido un error');
            return Redirect::to(URL::previous());
        }
    }
    /**
    * Función para registrar usuario
    */
    public function store(Request $request){
        $validator = Validator::make($request->all(), $this->rules, $this->messages);

        if ($validator->fails()) {
            return Redirect::to(URL::previous())->withInput()->withErrors($validator);
        }
        $cliente            =new Client();
        $cliente->email     =$request->input('email');
        $cliente->nombre    =$request->input('nombre');
        $cliente->documento =$request->input('documento');
        $cliente->direccion =$request->input('direccion');
        $cliente->save();
        if($cliente){
            Session::flash('success', 'Cliente Creado con Éxito!.');
            return Redirect::route('clients.index');
        }else{
            return Redirect::to(URL::previous())->withInput()->withErrors($validator);
        }
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $cliente     =Client::find($id);
            if(!$cliente ){
                return Redirect::to(URL::previous())->withInput();
            }
            return view('clientes.register',compact('cliente'));
        }catch(Exception $ex){
            Session::flash('error', 'Ha surgido un error');
            return Redirect::to(URL::previous());
        }
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
             $cliente     =Client::find($id);
            if(!$cliente ){
                Session::flash('error', 'No existe cliente');
                return Redirect::to(URL::previous())->withInput();
            }
            $validator = Validator::make($request->all(), $this->rules, $this->messages);
            if ($validator->fails()) {
                return Redirect::to(URL::previous())->withInput()->withErrors($validator);
            }
            $cliente->email     =$request->input('email');
            $cliente->nombre    =$request->input('nombre');
            $cliente->documento =$request->input('documento');
            $cliente->direccion =$request->input('direccion');
            $cliente->save();
            Session::flash('success', 'Cliente actualizado con Éxito!.');
            return Redirect::route('clients.index');
        }catch(Exception $ex){
            Session::flash('error', 'Ha surgido un error');
            return Redirect::to(URL::previous());
        }
    }
    /*
    *Eliminar cliente
    * @param  int  $id
    * @return \Illuminate\Http\Response
    **/

    public function destroy($id){
        if(!DB::table('clients')->where('id', $id)->delete()){
            Session::flash('error', 'Cliente no encontrado');
            return Redirect::route('clients.index');
        }
        Session::flash('success', 'Cliente eliminado');
        return Redirect::route('clients.index');
    }

    public function search(Request $request)
    {
        $search  =$request->input('search');
        $clients = Client::where('email','like',"%". $search."%")->orWhere('nombre','like',"%". $search."%")->orWhere('documento','like',"%". $search."%")->orWhere('direccion','like',"%". $search."%")->paginate(10);

        return view('clientes.index',compact('clients','search'));
    }
}

resources/views/clientes/index.blade.php
@extends('adminlte::page')
@section('content')
@include('edit')
<!--Begin::Row-->
<div class="row">
	<div class="col-xl-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">CLientes</h3>
            <a href="{{ route('clients.create') }}" class="btn btn-success float-right">
                Nuevo CLiente &nbsp;
                <i class="fa fa-user"></i>
            </a>
        </div>

        <div class="card-body">
            @include('flash_message')
            <table class="table table-striped table-compact" width="100%">
                <thead>
                    <tr class=" text-right">
                        <td colspan="5">
                            <form action="{{route('clientssearch')}}" method="GET">
                                <div class="input-group input-group-md">
                                    <input type="text" class="form-control" name="search" placeholder="Buscar..." value="{{($search)?$search:''}}">
                                    <span class="input-group-btn">
                                        <div class="btn-group">
                                            <button class="btn btn-success" type="submit"><i class="fa fa-search text-white"></i>Buscar!</button>
                                            <a href="{{route('clients.index')}}" class="btn btn-primary"><i class="fa fa-broom text-white"></i>Limpiar</a>
                                        </div>
                                    </span>
                                </div>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <th>Correo</th>
                        <th>Nombre</th>
                        <th>Documento</th>
                        <th>Dirección</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($clients as $key => $value)
                    <tr>
                        <td>{!! $value->email !!}</td>
                        <td>{!! $value->nombre !!}</td>
                        <td>{!! $value->documento !!}</td>
                        <td>{!! $value->direccion !!}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="First group">
                                <a href="{{route('clients.edit', $value)}}" class="btn btn-warning"  title="" ><i class="fa fa-edit"></i></a>
                                
                                <form method="POST" action="{{ route('clients.destroy',$value) }}">
                                     @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button type="submit" class="btn btn-info"><i class="fa fa-trash"></i></button>
                                </form>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr class=" text-center"><td colspan="5"><i class="fa fa-times-circle"></i>&nbsp;No se Encontraron resultados</td></tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="row   d-block mx-auto text-center ">
                    @if($clients)
                    <div class="col-md-12 d-block mx-auto text-center centerpagination">
                        @if(empty($search))
                        {{ $clients->appends([])->links() }}
                        @else
                        {{ $clients->appends(['search'=>$search])->links() }}
                        @endif
                        @if($clients->total()>0)
                        &nbsp;Registros&nbsp;<strong>{{$clients->count()}}</strong>&nbsp;de&nbsp;<strong>{{$clients->total()}}</strong>&nbsp;-&nbsp;Página&nbsp;<strong>{{$clients->currentPage()}}</strong>&nbsp;de&nbsp;<strong>{{$clients->lastPage()}}</strong>
                    </div>
                    @endif
                    @endif
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">

            </div>
        </div>
    </div>
</div>
<!--End::Row-->
@endsection

resources/views/clientes/register.blade.php
@extends('adminlte::page')
@section('content')
<!--Begin::Row-->
<div class="row">
	<div class="col-xl-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Editar Cliente</h3>
            <a href="{{ route('clients.index') }}" class="btn btn-success float-right">
                Clientes &nbsp;
                <i class="fa fa-list-alt"></i>
            </a>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        @if(empty($cliente))
        <form class="kt-form" action="{{ route('clients.store') }}" method="POST">
            @else
            <form method="POST" action="{{ route('clients.update',$cliente) }}">
                <input name="_method" type="hidden" value="PUT">
                @endif
                @csrf
                <div class="card-body">
                   @include('flash_message')
                   <div class="form-group">
                    <label class="">Correo Electrónico</label>
                    <input type="email" class="form-control" aria-describedby="emailHelp" autocomplete="off" placeholder="Ingrese correo electrónico" name="email" id="email" value="{{ empty($cliente)?'':$cliente->email }}">
                    <span class="form-text text-muted">Este correo no puede repetirse.</span>
                    @error('email')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Nombre</label>
                    <input type="text" class="form-control" aria-describedby="nombreHelp"  autocomplete="off" placeholder="Ingrese Nombre" name="nombre" id="nombre" value="{{ empty($cliente)?'':$cliente->nombre }}">
                    <span class="form-text text-muted">Nombre del Cliente.</span>
                    @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Documento</label>
                    <input type="text" class="form-control" aria-describedby="documentoHelp"  autocomplete="off" placeholder="Ingrese Documento" name="documento" id="documento" value="{{ empty($cliente)?'':$cliente->documento }}">
                    <span class="form-text text-muted">Documento del Cliente.</span>
                    @error('documento')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Direccion</label>
                    <textarea class="form-control" cols="20" rows="10" name='direccion' id='direccion'>{{ empty($cliente)?'':$cliente->direccion }}</textarea>
                    
                    <span class="form-text text-muted">Direccion del Cliente.</span>
                    @error('direccion')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <span class="kt-margin-left-10">o <a href="{{ route('clients.index') }}" class="kt-link kt-font-bold">Cancelar</a></span>
              </div>
          </div>
      </form>
  </div>
</div>
<!--End::Row-->
@endsection