routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'sentinel:admin,vendedor'], function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    /**
    * Rutas de usuario
    */    
    Route::group(['middleware' => 'sentinel:admin'], function () {
        Route::resource('users', 'AuthController');
        Route::get('usersactivate/{id}/{estado}', 'AuthController@activate')->name('usersactivate');
        Route::any('userssearch', 'AuthController@search')->name('userssearch');
    });
    Route::any('users_update/{user}', 'AuthController@show')->name('users_update');
    /**
    * Actualizar los datos de usuario por el propio usuario(Nombre, Apellido y Correo)
    */  
    Route::put('usersupdate/{id}', 'AuthController@update_user')->name('usersupdate');

    Route::resource('clients', 'ClienteController');
    Route::any('clientssearch', 'ClienteController@search')->name('clientssearch');
    
});
/*
*Rutas Publicas
*/
Route::post('sendlogin', 'AuthController@login')->name('sendlogin');
Route::get('userslogout', 'AuthController@logout')->name('userslogout');
Route::get('/', function () {
    //Sentinel::registerAndActivate(['email'=>'car@admin.com','password'=>'1234']);
    return view('vendor.adminlte.login');
})->name("/");

resources/views/usuarios/edit_profile.blade.php
@extends('adminlte::page')
@section('content')
@include('edit')
<div class="row">
	<div class="col-xl-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Editar Usuario</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="kt-form" action="{{ route('usersupdate',$user) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card-body">
              @include('flash_message')
              <div class="form-group">
                <label class="kt-font-boldest">Correo Electrónico</label>
                <input type="email" class="form-control" aria-describedby="emailHelp" autocomplete="off" placeholder="Ingrese correo electrónico" name="email" id="email" value="{{ empty($user)?'':$user->email }}" readonly="readonly">
                <span class="form-text text-muted">Este correo no puede repetirse.</span>
                @error('email')
                <span class="text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label class="kt-font-boldest">Nombres</label>
                <input type="text" class="form-control" aria-describedby="first_nameHelp"  autocomplete="off" placeholder="Ingrese Nombres" name="first_name" id="first_name" value="{{ empty($user)?'':$user->first_name }}">
                <span class="form-text text-muted">Nombre del usuario.</span>
                @error('first_name')
                <span class="text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label class="kt-font-boldest">Apellidos</label>
                <input type="text" class="form-control" aria-describedby="last_nameHelp"  autocomplete="off" placeholder="Ingrese Apellidos" name="last_name" id="last_name" value="{{ empty($user)?'':$user->last_name }}">
                <span class="form-text text-muted">Apellidos del usuario.</span>
                @error('last_name')
                <span class="text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            @if(!empty($user))
            <div class="form-group row">
                <div class="col-md-12 btn btn-bold btn-sm btn-font-sm  btn-label-warning"><i class="fa fa-info-circle"></i>&nbsp;Si no Desea cambiar contraseña deje en blanco</div>
            </div>
            @endif
            <div class="form-group">
                <label class="kt-font-boldest">Clave</label>
                <input type="password" class="form-control" id="password" name="password" autocomplete="off" placeholder="Clave">
                <span class="form-text text-muted">Para mayor seguridad, ingrese caracteres especiales, caracteres especiales y numeros.</span>
                @error('password')
                <span class="text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label class="kt-font-boldest">Confirmación de Clave</label>
                <input type="password" class="form-control" id="password_confirm" name="password_confirm" autocomplete="off" placeholder="Confirmación de Clave">
                <span class="form-text text-muted">Debe coincidir con al clave.</span>
                @error('password_confirm')
                <span class="text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
          <span class="">o <a href="{{ route('users.index') }}" class="">Cancelar</a></span>
      </div>
  </form>
</div>
</div>
</div>
@endsection

resources/views/usuarios/index.blade.php
@extends('adminlte::page')
@section('content')
@include('edit')
<!--Begin::Row-->
<div class="row">
	<div class="col-xl-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Usuarios</h3>
            <a href="{{ route('users.create') }}" class="btn btn-success float-right">
                Nuevo Usuario &nbsp;
                <i class="fa fa-user"></i>
            </a>
        </div>

        <div class="card-body">
            @include('flash_message')
            <table class="table table-striped table-compact" width="100%">
                <thead>
                    <tr class=" text-right">
                        <td colspan="4">
                            <form action="{{route('userssearch')}}" method="GET">
                                <div class="input-group input-group-md">
                                    <input type="text" class="form-control" name="search" placeholder="Buscar..." value="{{($search)?$search:''}}">
                                    <span class="input-group-btn">
                                        <div class="btn-group">
                                            <button class="btn btn-success" type="submit"><i class="fa fa-search text-white"></i>Buscar!</button>
                                            <a href="{{route('users.index')}}" class="btn btn-primary"><i class="fa fa-broom text-white"></i>Limpiar</a>
                                        </div>
                                    </span>
                                </div>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <th>Nombres</th>
                        <th>Email</th>
                        <th>Rol</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($users as $key => $value)
                    <tr>
                        <td>{!! $value->name !!}</td>
                        <td>{!! $value->email !!}</td>
                        <td>{!! (count($value->getRoles())>0)?$value->getRoles()->first()->name : '' !!}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="First group">
                                <a href="{{route('users.edit', $value)}}" class="btn btn-warning"  title="" ><i class="fa fa-edit"></i></a>
                                @if(Activation::completed($value))
                                <a href="{{route('usersactivate',[$value->id,0])}}" title="" class="btn btn-danger"><i class="fa fa-power-off"></i></a>
                                @else
                                <a href ="{{route('usersactivate',[$value->id,1])}}" class="btn btn-dark" title="" ><i class="fa fa-power-off"></i></a>
                                @endif
                                <form method="POST" action="{{ route('users.destroy',$value) }}">
                                     @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button type="submit" class="btn btn-info"><i class="fa fa-trash"></i></button>
                                </form>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr class=" text-center"><td colspan="4"><i class="fa fa-times-circle"></i>&nbsp;No se Encontraron resultados</td></tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="row   d-block mx-auto text-center ">
                    @if($users)
                    <div class="col-md-12 d-block mx-auto text-center centerpagination">
                        @if(empty($search))
                        {{ $users->appends([])->links() }}
                        @else
                        {{ $users->appends(['search'=>$search])->links() }}
                        @endif
                        @if($users->total()>0)
                        &nbsp;Registros&nbsp;<strong>{{$users->count()}}</strong>&nbsp;de&nbsp;<strong>{{$users->total()}}</strong>&nbsp;-&nbsp;Página&nbsp;<strong>{{$users->currentPage()}}</strong>&nbsp;de&nbsp;<strong>{{$users->lastPage()}}</strong>
                    </div>
                    @endif
                    @endif
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">

            </div>
        </div>
    </div>
</div>
<!--End::Row-->
@endsection

resources/views/usuarios/register.blade.php
@extends('adminlte::page')
@section('content')
<!--Begin::Row-->
<div class="row">
	<div class="col-xl-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Editar Usuario</h3>
            <a href="{{ route('users.index') }}" class="btn btn-success float-right">
                Usuarios &nbsp;
                <i class="fa fa-list-alt"></i>
            </a>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        @if(empty($user))
        <form class="kt-form" action="{{ route('users.store') }}" method="POST">
            @else
            <form method="POST" action="{{ route('users.update',$user) }}">
                <input name="_method" type="hidden" value="PUT">
                @endif
                @csrf
                <div class="card-body">
                   @include('flash_message')
                   <div class="form-group">
                    <label class="">Correo Electrónico</label>
                    <input type="email" class="form-control" aria-describedby="emailHelp" autocomplete="off" placeholder="Ingrese correo electrónico" name="email" id="email" value="{{ empty($user)?'':$user->email }}">
                    <span class="form-text text-muted">Este correo no puede repetirse.</span>
                    @error('email')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Nombres</label>
                    <input type="text" class="form-control" aria-describedby="first_nameHelp"  autocomplete="off" placeholder="Ingrese Nombres" name="first_name" id="first_name" value="{{ empty($user)?'':$user->first_name }}">
                    <span class="form-text text-muted">Nombre del usuario.</span>
                    @error('first_name')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Apellidos</label>
                    <input type="text" class="form-control" aria-describedby="last_nameHelp"  autocomplete="off" placeholder="Ingrese Apellidos" name="last_name" id="last_name" value="{{ empty($user)?'':$user->last_name }}">
                    <span class="form-text text-muted">Apellidos del usuario.</span>
                    @error('last_name')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                @if(!empty($user))
                <div class="form-group row">
                    <div class="col-md-12 btn btn-bold btn-sm btn-font-sm  btn-label-warning"><i class="fa fa-info-circle"></i>&nbsp;Si no Desea cambiar contraseña deje en blanco</div>
                </div>
                @endif
                <div class="form-group">
                    <label class="">Clave</label>
                    <input type="password" class="form-control" id="password" name="password" autocomplete="off" placeholder="Clave">
                    <span class="form-text text-muted">Para mayor seguridad, ingrese caracteres especiales, caracteres especiales y numeros.</span>
                    @error('password')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Confirmación de Clave</label>
                    <input type="password" class="form-control" id="password_confirm" name="password_confirm" autocomplete="off" placeholder="Confirmación de Clave">
                    <span class="form-text text-muted">Debe coincidir con al clave.</span>
                    @error('password_confirm')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Rol</label>
                    <select class="form-control select2" id="role_id" name="role_id">
                        <option value="">Seleccione</option>
                        @foreach ($roles as $key => $value)
                        @php 
                        $selected='';
                        @endphp
                        @if(!empty($user)&&$user->role_id==$key)
                        @php 
                        $selected='selected';
                        @endphp
                        @endif
                        <option {{ $selected }} value="{{$key}}">{{$value}}</option>
                        @endforeach
                    </select>
                    @error('role_id')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="">Activo</label><br>
                    <span class="">
                        <label>
                            <input type="checkbox" name="activate" id="activate" {{(isset($user)&&Activation::completed($user))?'checked="checked"':''}}>
                            <span></span>
                        </label>
                    </span>
                </div>

                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <span class="kt-margin-left-10">o <a href="{{ route('users.index') }}" class="kt-link kt-font-bold">Cancelar</a></span>
              </div>
          </div>
      </form>
  </div>
</div>
<!--End::Row-->
@endsection
@push('js')
<script type="text/javascript">
  $(document).ready(function() {
   $('.select2').select2({width:"100%"});
   @if(!empty($user))
   @if(!empty($user->getRoles()->first()->id))
   $('#role_id').val("{{$user->getRoles()->first()->id}}").trigger('change');
   @endif
   @endif
});
</script>
@endpush